Week1 submission
RnD-2020/manojdvs7-C-Learner pull request #13
Opened 2019-11-10 16:35 UTC by manojdvs7

2019-11-12 06:14 UTC, krushiraj requested changes
Please come up with changes and also good see the level of improvement in modularity.

2019-11-12 06:14 UTC, krushiraj commented on C-Arrays/src/maxPosNegSum.cpp
> +
I guess you don't need to write for loop twice you can have a single for and combine the logic that you are doing in to for loops.

2019-11-12 06:14 UTC, krushiraj commented on C-Arrays/src/oneTwoCount.cpp
> +		count[input[i] - 1]++;
Good logic

2019-11-12 06:14 UTC, krushiraj commented on C-Arrays/src/removeArrayDuplicates.cpp
> +				for (k = j; k < len; k++)
Do we really need 3 for loops nested? Try to optimize it.

2019-11-12 06:14 UTC, krushiraj commented on C-Arrays/src/scoresDescendingSort.cpp
> +}
Does this swap work expected. Because sometimes it may lose the reference to strings (here `name`). I'm not sure if it works, just check and get back here with your comments.

2019-11-12 06:14 UTC, krushiraj commented on C-Arrays/src/studentsCount.cpp
> +	for (int i = 0; i < len; i++)
Can you optimize this?

2019-11-12 06:14 UTC, krushiraj commented on C-Strings/src/KthIndexFromEnd.cpp
> +	return str[len - K];
What if the str length is 3 and K >= 3?

2019-11-12 06:14 UTC, krushiraj commented on C-Strings/src/NumbertoStr.cpp
> +int i = -1;
Avoid using globals. Please rewrite the code, without using global variables.

2019-11-12 06:14 UTC, krushiraj commented on C-Strings/src/commonWords.cpp
> +			while (str2[pos2] != '\0')
I think you can have this logic as modular as you wrote for other problems.

2019-11-14 13:42 UTC, manojdvs7 commented on C-Arrays/src/scoresDescendingSort.cpp
> +}
![image](https://user-images.githubusercontent.com/52916630/68862002-af4baf00-0712-11ea-9128-ddc4c8ca61b5.png)
yes bro,it is working fine

2019-11-18 17:17 UTC, krushiraj commented on C-Arrays/src/scoresDescendingSort.cpp
> +}
Okay. That's good then. just make sure that there are some compiler dependent things. So explore more.

2019-11-18 17:18 UTC, krushiraj approved these changes

2019-11-18 17:19 UTC, krushiraj commented on C-Arrays/src/maxPosNegSum.cpp
> +
Now this looks good.

2019-11-18 17:21 UTC, krushiraj approved these changes
All good. Merging this.

2019-11-18 17:21 UTC, merged