Unit1 assignments submission
RnD-2020/manojdvs7-C-Learner pull request #7
Opened 2019-10-14 07:19 UTC by manojdvs7

2019-10-15 04:55 UTC, krushiraj commented on C-NumberSystem/src/Swap.cpp
> +	*a = *a + *b;
Point to note and tip: As you have the pointers here. You can directly swap it by swapping the addresses also.

2019-10-15 05:01 UTC, krushiraj requested changes
Good to see that you finished the assignments too. I see the code logic is good but you need to concentrate on modularity. Break the code into functions where-ever possible. Everything else seems good and neat. Try not to have more than 10 lines in a function.

2019-10-15 05:01 UTC, krushiraj commented on C-Unit1-assignments/src/Assignment_02.cpp
> +		for (count = 0; count < acount; count++)
Can you this inner for loop and while loop extracted into 2 different functions and call it inside the outer for loop? So that it can make the code more modular and easy to understand and reusable!.

2019-10-15 05:01 UTC, krushiraj commented on C-Unit1-assignments/src/Assignment_03.cpp
> +
Even here can you make the code modular if possible?

2019-10-15 05:20 UTC, manojdvs7 commented on C-Unit1-assignments/src/Assignment_02.cpp
> +		for (count = 0; count < acount; count++)
I did that now. Is that ok bro?

2019-10-15 05:37 UTC, manojdvs7 commented on C-Unit1-assignments/src/Assignment_03.cpp
> +
I did that now. Is that ok bro?

2019-10-16 05:00 UTC, krushiraj approved these changes
All good in this.

2019-10-16 05:00 UTC, krushiraj commented on C-Unit1-assignments/src/Assignment_02.cpp
> +}
Good one. This looks neat and understandable function names. Keep this going in the next assignments too 😄

2019-10-16 05:01 UTC, krushiraj approved these changes
Everything is fine now. Merging this PR.

2019-10-16 05:01 UTC, krushiraj commented on C-Unit1-assignments/src/Assignment_03.cpp
> +
Yeah look good now.

2019-10-16 05:01 UTC, merged